global_costmap:
    footprint: [ [-0.1,-0.125], [0.5,-0.125], [0.5,0.125], [-0.1,0.125] ]
    # footprint_padding: 0.1
    transform_tolerance: 1.0
    # The frequency in Hz for the map to be updated
    update_frequency: 5.0
    # The frequency in Hz for the map to be publish display information
    publish_frequency: 5.0

    global_frame: map
    robot_base_frame: base_link
    # resolutions of the map in meters/cell
    resolution: 0.05

    rolling_window: false
    track_unknown_space: true

    plugins: 
        - {name: static_layer,    type: "costmap_2d::StaticLayer"} 
        - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

    static_layer:        
        map_topic: map 
        subscribe_to_updates: true

    obstacle_layer:
        observation_sources: laser_scan_sensor
        laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, 
            topic: scan, marking: true, clearing: true, inf_is_valid: true}

    inflation_layer:
        # the radius in meters to which the map inflates obstacle cost values
        inflation_radius: 0.1
        # scaling factor to apply to cost values during inflation
        cost_scaling_factor: 20.0
