global_costmap:
    footprint: [ [-0.1,-0.125], [0.5,-0.125], [0.5,0.125], [-0.1,0.125] ]
    # footprint_padding: 0.1
    transform_tolerance: 1.0
    update_frequency: 5.0
    publish_frequency: 5.0

    global_frame: map
    robot_base_frame: base_link
    # resolution: 0.05

    rolling_window: false
    track_unknown_space: true

    plugins: 
        - {name: static_layer,    type: "costmap_2d::StaticLayer"} 
        - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

    static_layer:        
        map_topic: map 
        subscribe_to_updates: true

    obstacle_layer:
        observation_sources: laser_scan_sensor
        laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

    inflation_layer:
        inflation_radius: 0.1
        cost_scaling_factor: 20.0
