# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

# The rate in Hz at which to run the control loop and send velocity commands to
controller_frequency: 5.0
controller_patience: 15.0

# The rate in Hz at which to run the global planning loop
planner_frequency: 5.0
planner_patience: 5.0

# How long in seconds to allow for oscillation before executing recovery behaviors
oscillation_timeout: 30.0
oscillation_distance: 0.5

# Racecar is not able to rotate in place
clearing_rotation_allowed: false
