# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 3.0

planner_frequency: 10.0
planner_patience: 5.0

oscillation_timeout: 30.0
oscillation_distance: 0.5

robot_radius: 0.3

# Racecar is not able to rotate in place
clearing_rotation_allowed: false
